#! /bin/sh

NETSFILE="/etc/tinc/nets.boot"

set -e

case "$1" in
    configure)
	if [ ! -e /dev/.devfsd ] ; then if [ ! -e /dev/.devfs ] ; then
		if [ ! -e /dev/net/tun ] ; then if [ ! -e /dev/tun ] ; then if [ -e /dev/MAKEDEV ]; then
			echo "Creating tun device..."
			cd /dev && ./MAKEDEV net/tun 2>/dev/null || ./MAKEDEV tun 2>/dev/null || echo "Failed to create tun device."
		fi; fi; fi
	fi; fi

	if [ ! -e $NETSFILE ] ; then
	    echo "## This file contains all names of the networks to be started on system startup when using sysvinit." > $NETSFILE
	    echo "## If you are using systemd, use systemctl enable tinc@netname to enable individual networks." >> $NETSFILE
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
